listen:
  # The IP address that will listen for connections
  address: 0.0.0.0
  # The port that will listen for connections
  port: 19133
remote:
  # The IP address of the remote server
  address: localhost
  # The port of the remote server
  port: 19132
  # The protocol version of the remote server
  # 389 - 1.14.0
  # 390 - 1.14.60
  # 407 - 1.16.0/1
  # 408 - 1.16.2
  protocol-version: 408

# If debug messages should be sent through console
debug-mode: false

# DO NOT TOUCH!
config-version: 1
